version: "3.8"

services:
  client:
    build:
      context: ../../apps/client
      dockerfile: ../../infra/docker/client/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8081
